### ISSUE TITLE
`SVGProps` doesn't implement `slot` event though `SVGSVGElement` should inherit from `Element`

### ISSUE THREAD

**Issue by mattclough1** [alex-kinokon/jsx-dom#102]
<img width="917" alt="Screenshot 2024-03-08 at 3 34 33 PM" src="https://github.com/alex-kinokon/jsx-dom/assets/8092237/c384e910-1d2b-4f54-861b-edf4618abf1e">

Trying to use the `slot` attribute on an `svg` tag, shows the error `Property 'slot' does not exist on type 'SVGProps<SVGSVGElement>'`, however `SVGElement` inherits the `slot` property from `Element` via this inheritance chain:

```mermaid
flowchart RL
    SVGSVGElement-->SVGGraphicsElement
    SVGGraphicsElement-->SVGElement
    SVGElement-->Element
```

**Comment by alex-kinokon** [comment]
PR welcome
