### ISSUE TITLE
TypeError: Class constructor Component cannot be invoked without 'new'

### ISSUE THREAD

**Issue by haferje** [alex-kinokon/jsx-dom#108]
We are using the latest version (v8.1.4) of jsx-dom just fine during development, but after promoting the code to production, we are encountering an error such as `TypeError: Class constructor Component cannot be invoked without 'new'`. After debugging the issue, it appears to be an error assoicated with the minification of jsx-dom in webpack in `mode: "production"`.

Webpack in production mode is defaulting to using the TerserJSPlugin, which is inadverantly stripping some code from jsx-dom that is annotated with `/* @__PURE__ */`. This removal is preventing class components that extend `React.Component` from getting assigned the `isReactComponent` property, which is what jsx-dom is using to determine class vs. functional components. The `initComponentClass()` method is then skipped and the class is trying to instantiate as a function, which then throws this uncaught exception.

If we inject into our own code the same `Object.defineProperties()` line of jsx-dom that is getting stripped out, our production build seems to work as intended.  Was this annotation in the code intentional? This particular line was added to fix issue #86, but seems unrelated.

I have attached a [sandbox.zip](https://github.com/user-attachments/files/16700600/sandbox.zip) file containing a minimal example project that should demonstrate the issue, where `index.tsx` contains a bit of code that can be toggled, showing the `Object.defineProperties` line is required.

Thank you!

EDIT: I've also set up a [codesandbox](https://codesandbox.io/p/devbox/ts-wp-jsxdom-gjmqcz) if that is preferred over the attached zip.

**Comment by alex-kinokon** [comment]
Published as `8.1.5`. It is now checked by `Component.isComponent`, a static class property.

**Comment by haferje** [comment]
The new v8.1.5 seems to fix the issue in our example project!
Thank you again for the quick turn-around!
