### ISSUE TITLE
Uncaught TypeError: (0 , _jsxDevRuntime.jsxDEV) is not a function

### ISSUE THREAD

**Issue by remarkablemark** [alex-kinokon/jsx-dom#84]
I'm trying to run `jsx-dom` in my [Parcel](https://parceljs.org/) app but I'm getting the error:

```
Uncaught TypeError: (0 , _jsxDevRuntime.jsxDEV) is not a function
    at 41oNQ.jsx-dom/jsx-dev-runtime (app.tsx:5:27)
    at newRequire (index.303574b1.js:71:24)
    at index.303574b1.js:122:5
    at index.303574b1.js:145:3
```

![Screen Shot 2023-01-12 at 11 45 51 PM](https://user-images.githubusercontent.com/10594555/212239674-b7c4a099-6481-41f5-9ae6-441c1545ef4f.png)

I believe to fix this error, `jsxDEV` needs to be exported from [jsx-runtime.ts](https://github.com/alex-kinokon/jsx-dom/blob/1030d03/src/jsx-runtime.ts)

See reproducible example: https://github.com/remarkablemark/parcel-jsx-dom-example

**Comment by alex-kinokon** [comment]
Published as 8.0.4.
