### ISSUE TITLE
Type 'ClassList' is not assignable to type '{ [key: string]: boolean; }'

### ISSUE THREAD

**Issue by aleclarson** [alex-kinokon/jsx-dom#86]
I have a component whose props are `JSX.IntrinsicElements['div']` and I want to pass its `props.class` value into a `class` array prop of a `<div>` element (effectively merging the `props.class` value with other classes), but the `ClassNames` type does not allow `ClassList` in the `ClassName[]` type.

Is this a runtime limitation or just an issue with the `ClassName` type?

**Example:**
```jsx
function Foo(props) {
  //                         ↓ Type 'ClassList' is not assignable to type '{ [key: string]: boolean; }'
  return <div class={["foo", props.class]} />
}
```

**Comment by aleclarson** [comment]
https://github.com/alex-kinokon/jsx-dom/blob/b316c8604936eb9d5bcafc89dcb46d7f52876f45/types/index.d.ts#L38

Shouldn't this type support both `BasicClassList` and `DOMTokenList`? Otherwise, #86 is still an issue.

**Comment by alex-kinokon** [comment]
PR welcome. Sorry I’m a bit busy right now.

**Comment by aleclarson** [comment]
No need to apologize. Thanks for the library :)
