### ISSUE TITLE
Issues working with React Storybook

### ISSUE THREAD

**Issue by haferje** [alex-kinokon/jsx-dom#88]
I am trying to use Storybook to develop a UI framework with jsx-dom. I understand this is not ideal (using actual React in Storybook to develop a React-like library with jsx-dom), but I was wondering if it is possible to mix the two?

I have defined my jsx-dom Button as so
```
export const Button = (options: ButtonOptions): HTMLButtonElement => {
    return (
        <button type="button">
            Hello World
        </button>
    ) as HTMLButtonElement;
};
```

Currently, when I define a Storybook story template, using my jsx-dom Button
```
const Template = (args) => <Button {...args}></Button>;
```
I get the error `Objects are not valid as a React child (found: [object HTMLButtonElement]). If you meant to render a collection of children, use an array instead.`
Which makes sense, because jsx-dom compiles it to an HTMLElement

If I include the following Container hack
```
import React from 'react';
class Container extends React.Component {
    render() {
        return <div ref={(ref) => ref?.appendChild(this.props.child)}></div>;
    }
}
```
Then I can properly render the jsx-dom component using
```
const Template = (args) => <Container child={Button(args)}></Container>;
```
But this is not an ideal solution for all my stories.

If I install Storybook to a separate folder, I can even get it to work with
```
const Template = (args) => Button(args);
```

 
Is it possible to use jsx-dom to return a ReactElement so I can have it work properly with Storybook stories, or is there any other trick to getting it to work?

Thank you!

**Comment by alex-kinokon** [comment]
You can change the return type of `Button` to `any`. Your `<Button {...attrs} />` call will still be correctly type-checked.
