### ISSUE TITLE
Support for disabled property of link: <link href="..." disabled />

### ISSUE THREAD

**Issue by caph1993** [alex-kinokon/jsx-dom#97]
Hello, when I try to use the [disabled](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement#instance_properties) property in a link element, I get a type error:

```
Property 'disabled' does not exist on type 'DetailedHTMLProps<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>'.ts(2322)
```

I wonder if it can be added to the type declaration to get rid of the editor warning.

**Comment by alex-kinokon** [comment]
PR welcome
